### ISSUE TITLE
"Input stream exhausted" error on autosign command

### ISSUE THREAD

**Issue by rtkmhart** [VendaTech/chef-cookbook-ssl#6]
I was getting this error when running autosign:

$ chef-ssl autosign --ca-path ~/tmp/mysubca --ca-name="Chef Test CA" --trace
<snip for brevity>
Sign this? (yes or no)
/Library/Ruby/Gems/1.8/gems/highline-1.6.15/lib/highline.rb:793:in `get_line': The input stream is exhausted. (EOFError)
    from /Library/Ruby/Gems/1.8/gems/highline-1.6.15/lib/highline.rb:818:in`get_response'
    from /Library/Ruby/Gems/1.8/gems/highline-1.6.15/lib/highline.rb:248:in `ask'
    from /Library/Ruby/Gems/1.8/gems/highline-1.6.15/lib/highline.rb:347:in`choose'
    from /Library/Ruby/Gems/1.8/gems/chef-ssl-client-1.0.4/lib/chef-ssl/command.rb:235
    from /Library/Ruby/Gems/1.8/gems/chef-ssl-client-1.0.4/lib/chef-ssl/client.rb:55:in `ca_search'
    from /Library/Ruby/Gems/1.8/gems/chef-ssl-client-1.0.4/lib/chef-ssl/client.rb:53:in`each'
    from /Library/Ruby/Gems/1.8/gems/chef-ssl-client-1.0.4/lib/chef-ssl/client.rb:53:in `ca_search'
    from /Library/Ruby/Gems/1.8/gems/chef-ssl-client-1.0.4/lib/chef-ssl/client.rb:52:in`each'
    from /Library/Ruby/Gems/1.8/gems/chef-ssl-client-1.0.4/lib/chef-ssl/client.rb:52:in `ca_search'
    from /Library/Ruby/Gems/1.8/gems/chef-ssl-client-1.0.4/lib/chef-ssl/command.rb:225
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.3/lib/commander/command.rb:180:in`call'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.3/lib/commander/command.rb:155:in`run'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.3/lib/commander/runner.rb:402:in `run_active_command'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.3/lib/commander/runner.rb:78:in`run!'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.3/lib/commander/delegates.rb:7:in `run!'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.3/lib/commander/import.rb:10
    from /usr/bin/chef-ssl:23

I worked around this by adding this line to client-gem/lib/chef-ssl/command.rb:234

  HighLine.track_eof = false

I suspect it's my Mac, lots of articles about this error on mac. My specific environment:
OSX 10.8.2
ruby -v: ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
highline: 1.6.15

Not looking for a fix, just putting it here in case anyone else runs into it.

mike

**Comment by chrisa** [comment]
We don't see this, even on the Mac, though our Chef environment is exclusively Ruby 1.9.2. I'll definitely experiment with this though as it seems there's demand for 1.8 compatibility (see #4).

Thanks for the feedback!
